### ISSUE TITLE
Video thumbnail support

### ISSUE THREAD

**Issue by TLHP** [rtoshiro/FullscreenVideoView#10]
Would be nice if it shows also video thumbnail :)

Cheer

**Comment by nejifresh** [comment]
My app keeps crashing when i use this library in an Adapter. Here's the error:
  java.lang.NullPointerException
                                                                            at com.github.rtoshiro.view.video.FullscreenVideoView.surfaceCreated(FullscreenVideoView.java:176)
                                                                            at android.view.SurfaceView.updateWindow(SurfaceView.java:662)
                                                                            at android.view.SurfaceView.access$000(SurfaceView.java:90)
                                                                            at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:195)
                                                                            at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
                                                                            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2191)
                                                                            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1189)
                                                                            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6223)
                                                                            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
                                                                            at android.view.Choreographer.doCallbacks(Choreographer.java:591)
                                                                            at android.view.Choreographer.doFrame(Choreographer.java:560)
                                                                            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
                                                                            at android.os.Handler.handleCallback(Handler.java:808)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:103)
                                                                            at android.os.Looper.loop(Looper.java:193)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5336)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by amanzan** [comment]
+1. Any workaround for having a thumbnail? I tried to set the background to the parent FrameLayout, but it does nothing

**Comment by sovoereign** [comment]
have you added thumbnail facility to this video player?
