### ISSUE TITLE
android.view.ViewGroup$LayoutParams android.view.SurfaceView.getLayoutParams() is Null

### ISSUE THREAD

**Issue by Monster-king** [rtoshiro/FullscreenVideoView#34]
I'm using your player in the recyclerview. I have seen the issue with recyclerview and changed version of the library to 1.1.3a-SNAPSHOT, but i get the error. 
Here stacktrace:
```
 E/MediaPlayer: Should have subtitle controller already set
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: uz.demo.demoapp, PID: 32093
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewGroup$LayoutParams android.view.SurfaceView.getLayoutParams()' on a null object reference
                                                                         at com.github.rtoshiro.view.video.FullscreenVideoView$2.run(FullscreenVideoView.java:593)
                                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:145)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6917)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

And here the code where i bind recyclerview items:
```
public void bindView(NewsFeedModel feedItem) {
        this.newsFeedItem = feedItem;
        btnLike.setImageResource(feedItem.isLiked ? R.drawable.ic_like_active : R.drawable.ic_like_passive);
        tsLikesCounter.setCurrentText(cardView.getResources().getQuantityString(
                R.plurals.likes_count, feedItem.likesCount, feedItem.likesCount
        ));
        userImage.setImageURI(Uri.parse(feedItem.author.avatar));
        contentImage.setImageURI(Uri.parse(feedItem.photo));
        userType.setText(feedItem.author.category);
        userName.setText(feedItem.author.fullname);
        contentText.setText(feedItem.content);
        time.setText(Utils.formatTime(feedItem.time));
        if (videoLayout != null && isFirsttime) {
            isFirsttime = false;
            videoLayout.setActivity(mActivity);
            try {
                videoLayout.setVideoURI(Uri.parse("http://content1.mnogo.uz/artist/4096/videoplayback.4.mp4"));
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
```

**Comment by rtoshiro** [comment]
Hi @Monster-king 
I have released a new version with this fix.
Thank you.
