### ISSUE TITLE
URL is dummy but receving following error

### ISSUE THREAD

**Issue by sonaypsi** [rtoshiro/FullscreenVideoView#38]
MediaPlayer: setDataSource: IOException! uri=http://example.in/1494927784.mp4
                                                       java.io.FileNotFoundException: No content provider: http://example.in/1494927784.mp4
                                                           at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1137)
                                                           at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:975)
                                                           at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:902)
                                                           at android.media.MediaPlayer.setDataSource(MediaPlayer.java:992)
                                                           at android.media.MediaPlayer.setDataSource(MediaPlayer.java:966)
                                                           at com.github.rtoshiro.view.video.FullscreenVideoView.setVideoURI(FullscreenVideoView.java:814)
                                                           at com.petnod.activity.VideoviewActivity.videoPlay(VideoviewActivity.java:70)
                                                           at com.petnod.activity.VideoviewActivity.onCreate(VideoviewActivity.java:37)
                                                           at android.app.Activity.performCreate(Activity.java:6005)
                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2446)
                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2555)
                                                           at android.app.ActivityThread.access$800(ActivityThread.java:176)
                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1437)
                                                           at android.os.Handler.dispatchMessage(Handler.java:111)
                                                           at android.os.Looper.loop(Looper.java:194)
                                                           at android.app.ActivityThread.main(ActivityThread.java:5576)
                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)

**Comment by rtoshiro** [comment]
Hi @sonaypsi 
Does it work with native VideoView?
